In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split

In [37]:
# read data
sales = pd.read_csv("Online_Sales.csv")
customers = pd.read_excel("CustomersData.xlsx")
tax = pd.read_excel("Tax_amount.xlsx")
discount = pd.read_csv("Discount_Coupon.csv")
marketing = pd.read_csv("Marketing_Spend.csv")

In [38]:
sales.head(5)

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status
0,17850,16679,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
1,17850,16680,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
2,17850,16681,1/1/2019,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used
3,17850,16682,1/1/2019,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used
4,17850,16682,1/1/2019,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used

In [39]:
sales.info()
sales.describe()
sales.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           52924 non-null  int64
 1   Transaction_ID       52924 non-null  int64
 2   Transaction_Date     52924 non-null  str
 3   Product_SKU          52924 non-null  str
 4   Product_Description  52924 non-null  str
 5   Product_Category     52924 non-null  str
 6   Quantity             52924 non-null  int64
 7   Avg_Price            52924 non-null  float64
 8   Delivery_Charges     52924 non-null  float64
 9   Coupon_Status        52924 non-null  str
dtypes: float64(2), int64(3), str(5)
memory usage: 7.6 MB

CustomerID             0
Transaction_ID         0
Transaction_Date       0
Product_SKU            0
Product_Description    0
Product_Category       0
Quantity               0
Avg_Price              0
Delivery_Charges       0
Coupon_Status          0
dtype: int64

In [40]:
customers.head()

   CustomerID Gender    Location  Tenure_Months
0       17850      M     Chicago             12
1       13047      M  California             43
2       12583      M     Chicago             33
3       13748      F  California             30
4       15100      M  California             49

In [41]:
customers.info()
customers.describe()
customers.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     1468 non-null   int64
 1   Gender         1468 non-null   str
 2   Location       1468 non-null   str
 3   Tenure_Months  1468 non-null   int64
dtypes: int64(2), str(2)
memory usage: 60.0 KB

CustomerID       0
Gender           0
Location         0
Tenure_Months    0
dtype: int64

In [42]:
tax.head()

  Product_Category   GST
0         Nest-USA  0.10
1           Office  0.10
2          Apparel  0.18
3             Bags  0.18
4        Drinkware  0.18

In [43]:
tax.info()
tax.describe()
tax.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_Category  20 non-null     str
 1   GST               20 non-null     float64
dtypes: float64(1), str(1)
memory usage: 614.0 bytes

Product_Category    0
GST                 0
dtype: int64

In [44]:
discount.head()

  Month Product_Category Coupon_Code  Discount_pct
0   Jan          Apparel      SALE10            10
1   Feb          Apparel      SALE20            20
2   Mar          Apparel      SALE30            30
3   Jan         Nest-USA      ELEC10            10
4   Feb         Nest-USA      ELEC20            20

In [45]:
discount.info()
discount.describe()
discount.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Month             204 non-null    str
 1   Product_Category  204 non-null    str
 2   Coupon_Code       204 non-null    str
 3   Discount_pct      204 non-null    int64
dtypes: int64(1), str(3)
memory usage: 9.9 KB

Month               0
Product_Category    0
Coupon_Code         0
Discount_pct        0
dtype: int64

In [46]:
marketing.head()

       Date  Offline_Spend  Online_Spend
0  1/1/2019           4500       2424.50
1  1/2/2019           4500       3480.36
2  1/3/2019           4500       1576.38
3  1/4/2019           4500       2928.55
4  1/5/2019           4500       4055.30

In [47]:
marketing.info()
marketing.describe()
marketing.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           365 non-null    str
 1   Offline_Spend  365 non-null    int64
 2   Online_Spend   365 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 11.9 KB

Date             0
Offline_Spend    0
Online_Spend     0
dtype: int64

In [50]:

# Tạo cột Month để join với Discount_Coupon
sales["Transaction_Date"] = pd.to_datetime(sales["Transaction_Date"])
sales["Month"] = sales["Transaction_Date"].dt.strftime("%b")  # "Jan", "Feb"...

# Join từng bảng vào sales
df = sales.merge(customers, on="CustomerID",         how="left")
df = df.merge(tax,          on="Product_Category",   how="left")
df = df.merge(discount,     on=["Product_Category", "Month"], how="left")

marketing["Transaction_Date"] = pd.to_datetime(marketing["Date"])
df = df.merge(marketing[["Transaction_Date", "Offline_Spend", "Online_Spend"]],
              on="Transaction_Date", how="left")

print("Shape:", df.shape)
df.columns.tolist()

Shape: (52924, 20)

['CustomerID',
 'Transaction_ID',
 'Transaction_Date',
 'Product_SKU',
 'Product_Description',
 'Product_Category',
 'Quantity',
 'Avg_Price',
 'Delivery_Charges',
 'Coupon_Status',
 'Month',
 'Trans_Date_str',
 'Gender',
 'Location',
 'Tenure_Months',
 'GST',
 'Coupon_Code',
 'Discount_pct',
 'Offline_Spend',
 'Online_Spend']

In [51]:
df.head()

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,Month,Trans_Date_str,Gender,Location,Tenure_Months,GST,Coupon_Code,Discount_pct,Offline_Spend,Online_Spend
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,Jan,2019-01-01 00:00:00,M,Chicago,12,0.10,ELEC10,10.0,4500,2424.5
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,Jan,2019-01-01 00:00:00,M,Chicago,12,0.10,ELEC10,10.0,4500,2424.5
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used,Jan,2019-01-01 00:00:00,M,Chicago,12,0.10,OFF10,10.0,4500,2424.5
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used,Jan,2019-01-01 00:00:00,M,Chicago,12,0.18,SALE10,10.0,4500,2424.5
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used,Jan,2019-01-01 00:00:00,M,Chicago,12,0.18,AIO10,10.0,4500,2424.5